# Generated by Django 5.0.2 on 2024-05-02 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ShopNest", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bewertung",
            name="bewertung",
        ),
        migrations.RemoveField(
            model_name="bewertung",
            name="datum",
        ),
        migrations.RemoveField(
            model_name="bewertung",
            name="kommentar",
        ),
        migrations.AlterField(
            model_name="bewertung",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
